INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (1,'S','FASE 1 - DEFINIÇÃO DOS PLANOS E PLANEJAMENTO',0,NULL);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (11,'S','PLANEJAMENTO DO PROJETO',0,1);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (11001,'A','          Gerênciamento do Projeto',705,45,11);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (11002,'A','          Elaboração do Cronograma de Implantação',40,11);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (11003,'A','          Definição do Comite de Implantação',8,11);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (11002,'A','          Reunião de Apresentação do Escopo do Projeto',8,11);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (11004,'A','          Distribuição de Tarefas Iniciais junto ao Cliente',16,11);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (11005,'A','          Definição de Empresas e Filiais',12,11);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (13,'S','DEFINIÇÃO DOS MODELOS DE PLANO',0,1);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (13001,'A','          Contábil',32,13);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (13002,'A','          Financeiro',16,13);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (13003,'A','          Centro de Custos',16,13);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (13004,'A','          Definir modelos de Livros Contábeis',8,13);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (14,'S','DEFINIÇÃO DE EQUIPE DE IMPLANTAÇÃO',0,1);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (14001,'A','          Apresentação do Projeto junto aos Consultores',4,14);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (15,'S','INSTALAÇÕES',0,1);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (15001,'A','          Intalação do Ambiente Meddleware',8,15);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (15002,'A','          Instalação Senior Documentos Eletrônicos',16,15);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (15003,'A','          Instalação dos Produtos Senior',8,15);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3,'S','FASE 2 - ATIVIDADES INICIAIS',0,NULL);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (31,'S','IMPORTAÇÃO DE PLANOS',0,3);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3101,'A','          Importação Plano Contábil',8,31);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3102,'A','          Importação Plano Financeiro',8,31);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3103,'A','          Importação Plano de Centro de Custos',8,31);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3104,'A','          Configuração de Contas Planilha de Importação',8,31);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (32,'S','REPASSE DE ATIVIDADES',0,3);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3201,'A','          Definição Contábil de Todos os Documentos Fiscais Separados (Repasse de Atividade ao Cliente)',4,32);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (33,'S','LEVANTAMENTOS E DOCUMENTAÇÕES',0,3);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301,'S','       CADASTROS GERAIS',0,33);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001,'S','              DEFINIÇÃO DE PRODUTOS/SERVIÇOS',0,3301);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001001,'A','                            Origem',4,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001002,'A','                            Familia',16,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001003,'A','                            Produto e Derivação - Ficha Técnica',8,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001004,'A','                            Serviços',8,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001005,'A','                            Pré-Definição de Rateios Familia',24,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001006,'A','                            Pré-Definição de Rateios Serviços',8,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001007,'A','                            ------------------------------------------------',0,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001008,'A','                            Mascara de Código de Produtos',4,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001009,'A','                            Mascara de Código Derivação',2,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001010,'A','                            Mascaras de Lote',2,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001011,'A','                            Unidades de Medias e Conversões',4,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001012,'A','                            Levantamento de Regras por Evento para Validações Extras de Cadastros                            ',2,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001013,'A','                            -------------------------------------------------',0,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301001014,'A','                            Documentação e Formalização',40,3301001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002,'S','              PESSOAS',0,3301);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002001,'A','                            Clientes e Fornecedores',2,3301002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002002,'A','                            Transportadoras',2,3301002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002003,'A','                            Representantes',2,3301002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002004,'A','                            Usuários',16,3301002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002005,'A','                            Endenreços de Entrega',2,3301002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002006,'A','                            Origem de Mercadorias',2,3301002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002007,'A','                            -------------------------------------------------',0,3301002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002008,'A','                            Levantamento de Regras por Evento para validações extras de Cadastros',2,3301002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002009,'A','                            -------------------------------------------------',0,3301002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301002010,'A','                            Documentação de Formalização',8,3301002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301003,'S','            DEFINIÇÃO DE DEPÓSITOS / LOCAIS',0,3301);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301003001,'A','                            Cadastro de Depósito',8,3301003);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301003002,'A','                            Cadastro de Localização',4,3301003);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301003003,'A','                            ---------------------------------------------------',0,3301003);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301003004,'A','                            Documentação e Formalização',4,3301003);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004,'S','            COMERCIAL',0,3301);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004001,'A','                            Tabelas de Preços',1,3301004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004002,'A','                            Condições de Pagamento',1,3301004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004003,'A','                            Formas de Pagamento',1,3301004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004004,'A','                            Séries de Notas Fiscais',1,3301004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004005,'A','                            Mensagens de Notas Fiscais',4,3301004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004006,'A','                            Parametros por Estado',4,3301004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004007,'A','                            Reduções/ Acréscimos de Base de Calculo',4,3301004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004008,'A','                            Tabelas de ICMS Especial',4,3301004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004009,'A','                            ----------------------------------------------',0,3301004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3301004010,'A','                            Documentação e Formalização',8,3301004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302,'S','            MERCADO',0,33);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302004,'A','                   LEVANTAMENTO DE PROCESSOS / DOCUMENTAÇÕES',0,3302);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302004001,'A','                                     Operações de Negociação (Contratos / Pedidos)',20,3302004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302004002,'A','                                     Operações de Faturamento',20,3302004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302004003,'A','                                     Operações de Negociação X Operações de Faturamento',4,3302004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302004004,'A','                                     Operações de Faturamento X Mensagens de Notas Fiscais',4,3302004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302004005,'A','                                     Relatórios Gerênciais',8,3302004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302004006,'A','                                     ------------------------------------------',0,3302004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302004007,'A','                                     Levantamento de Mudanças do comportamento Padrão do Sistema (Inclusão de Regras/Identificadores)',16,3302004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302004008,'A','                                     ------------------------------------------',0,3302004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302004009,'A','                                     Documentação e Formalização',40,3302004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302005,'A','                   DOCUMENTOS ELETRÔNICOS',0,3302);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302005001,'A','                                     Definição dos Tipos de Doc. Eletrônico (NF-e,NF-s,MDF-e entre outros)',16,3302005);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302005002,'A','                                     Modelo de DANFE',2,3302005);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302005003,'A','                                     Recebimento Eletrônico',4,3302005);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302005004,'A','                                     -----------------------------------------',0,3302005);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3302005005,'A','                                     Documentação e Formalização',8,3302005);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303,'S','            SUPRIMENTOS',0,33);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002,'S','                   LEVANTAMENTO DE PROCESSOS / DOCUMENTAÇÕES',0,3303);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002001,'A','                                     Inventário de Estoques',4,3303002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002004,'A','                                     Politica Opercional dos Almoxarifados',12,3303002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002005,'A','                                     Politica de Reposição de Estoques',4,3303002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002006,'A','                                     Processo de Compra / Aprovação de Compras',8,3303002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002007,'A','                                     Ordens de Compra / Contratos / Aprovação',20,3303002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002008,'A','                                     Mapeamento de Orações de Entrada X Saida',8,3303002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002009,'A','                                     Recebimento de Notas Fiscais / Aprovações / Conferência',32,3303002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002012,'A','                                     Levantamento de Mudanças do comportamento Padrão do Sistema (Inclusão de Regras/Identificadores)',24,3303002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002013,'A','                                     ----------------------------------------',0,3303002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3303002014,'A','                                     Documentação e Formalização',40,3303002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304,'S','            FINANÇAS',0,33);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304001,'S','                   CADASTROS GERAIS',0,3304);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304001001,'A','                                     Cadastro de Tipos de Título',8,3304001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304001002,'A','                                     Contas Internas',8,3304001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304001003,'A','                                     Cadastro de Natureza de Gastos',4,3304001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304001004,'A','                                     Portadores / Carteira',2,3304001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304001005,'A','                                     Tipos de Documento',2,3304001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002,'S','                   LEVANTAMENTO DE PROCESSOS / DOCUMENTAÇÕES',0,3304);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002001,'A','                                     Contas A Receber',16,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002002,'A','                                     Contas A Pagar / Aprovações',16,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002003,'A','                                     Tesouraria',8,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002004,'A','                                     Fluxo de Caixa',8,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002005,'A','                                     Contratos de Financiamento',8,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002006,'A','                                     Aplicação Financeira',8,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002009,'A','                                     Pagamento Eletrônico',4,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002010,'A','                                     Cobrança Escritural',4,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002011,'A','                                     Extratos Bancários',2,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002012,'A','                                     ---------------------------------------',0,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002013,'A','                                     Levantamento de Mudanças do comportamento Padrão do Sistema (Inclusão de Regras/Identificadores)',24,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002014,'A','                                     ---------------------------------------',0,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3304002015,'A','                                     Documentação e Formalização',40,3304002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305,'S','            CONTROLADORIA',0,33);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001,'S','                   CADASTROS',0,3305);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001001,'A','                                     Histórico Padrão',8,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001002,'A','                                     Formas de Contabilização',24,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001010,'A','                                     --------------------------------------',0,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001011,'A','                                     Tributos',8,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001012,'A','                                     Tabelas de Tributação',8,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001013,'A','                                     Dispositivos e Equipamentos Fiscais',4,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001014,'A','                                     Composição Base de Faturamento (Bruto/liquido)',4,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001020,'A','                                     ---------------------------------------',0,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001021,'A','                                     Espécies de Imobilizado',8,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001022,'A','                                     Definições de Imobilizado',8,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001023,'A','                                     ---------------------------------------',0,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305001024,'A','                                     Documentação e Formalização',8,3305001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305002,'S','                   CONTABILIDADE',0,3305);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305002001,'A','                                     Lançamentos Progamados',2,3305002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305002002,'A','                                     Metodologia de Apuração de Custo',16,3305002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305002003,'A','                                     Obrigações / Livros Contábeis',4,3305002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305002004,'A','                                     ---------------------------------------',0,3305002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305002005,'A','                                     Documentação e Formalização',4,3305002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305003,'S','                   PATRIMÔNIO',0,3305);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305003001,'A','                                     Inventário Patrimônial',8,3305003);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305003002,'A','                                     Formas de Calculo Depreciação',4,3305003);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305003003,'A','                                     Relatórios Gerenciais',4,3305003);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305003004,'A','                                     --------------------------------------',0,3305003);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305003005,'A','                                     Documentação e Formalização',8,3305003);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305004,'S','                   TRIBUTOS',0,3305);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305004001,'A','                                     Apuração de Impostos',8,3305004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305004002,'A','                                     Obrigações Fiscais',8,3305004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305004003,'A','                                     CIAP - Crédito de ICMS Ativo Imobilizado',4,3305004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305004004,'A','                                     --------------------------------------',0,3305004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3305004005,'A','                                     Documentação e Formalização',8,3305004);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3306,'S','                   GESTÃO ORÇAMENTÁRIA',0,33);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3306001,'A','                                     Projetos / Fase',8,3306);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3306002,'A','                                     Orçamento por Projetos e Fase',8,3306);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307,'S','            MANUFATURA',0,33);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307001,'S','                   CADASTROS GERAIS',0,3307);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307001001,'A','                                     Centros de Recursos',8,3307001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307001002,'A','                                     Estágios',8,3307001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307001003,'A','                                     Turnos de Trabalho',2,3307001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307001004,'A','                                     Células de Produção',8,3307001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307001005,'A','                                     Motivos de Parada',2,3307001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307001006,'A','                                     Operadores',4,3307001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307001007,'A','                                     Operações',4,3307001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307001008,'A','                                     Ações Corretivas',4,3307001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307001009,'A','                                     Calendário Industrial',4,3307001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307002,'S','                   LEVANTAMENTO DE PROCESSOS / DOCUMENTAÇÕES',0,3307);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307002001,'A','                                     Layout Industrial',8,3307002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307002002,'A','                                     Níveis de produtos acabados',32,3307002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307002003,'A','                                     Método para apontamentos',8,3307002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307002004,'A','                                     Controle de remesse para industrialização',4,3307002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307002005,'A','                                     ---------------------------------------',0,3307002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3307002006,'A','                                     Documentação e Formalização',24,3307002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308,'S','            QUALIDADE',0,33);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308001,'S','                   CADASTROS GERAIS',0,3308);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308001001,'A','                                     Tipos de Documentos',4,3308001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308001002,'A','                                     Requisitos ISO/Qualidade',8,3308001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308001003,'A','                                     Inspeções/Verificações',4,3308001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308001004,'A','                                     Planos de Inspeções',8,3308001);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308002,'S','                   LEVANTAMENTO DE PROCESSOS / DOCUMENTAÇÕES',0,3308);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308002001,'A','                                     Documentos de Qualidade',8,3308002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308002002,'A','                                     Pontos de inspeções',8,3308002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308002003,'A','                                     Avaliação de Fornecedores',8,3308002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308002004,'A','                                     ---------------------------------------',0,3308002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3308002005,'A','                                     Documentação e Formalização',8,3308002);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (34,'S','TREINAMENTO EQUIPE DE TI EMPRESA',0,3);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3401,'A','       Ferramentas',24,34);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (3402,'A','       Customizações',40,34);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6,'S','FASE 3 - PARAMETRIZAÇÃO ERP SENIOR',0,NULL);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (61,'S','       SUPRIMENTOS',0,6);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6101,'S','            GESTÃO DE ESTOQUES',0,61);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6101001,'A','                          Paramentros por Filial',4,6101);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6101002,'A','                          Cadastro / Revisão de Operações de Estoque',8,6101);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6101003,'A','                          Aprovação de Requsições',4,6101);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6101004,'A','                          Análise de Reposição',8,6101);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6101005,'A','                          Controle de Inventário',2,6101);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6101006,'A','                          Desenvolvimento de Regras Levantadas para Alteração do Comportamento do Módulo',0,6101);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6101007,'A','                          Prototipação da Gestão de Estoques',16,6101);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6102,'S','            GESTÃO DE COMPRAS',0,61);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6102001,'A','                          Parâmetros por Filiais',8,6102);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6102002,'A','                          Cadastro / Revisão de Operações de Compra/Solicitação',8,6102);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6102003,'A','                          Aprovações (Solicitação / Processo de Compra / Ordem Compra / Contratos)',8,6102);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6102004,'A','                          Desenvolvimento de Regras Levantadas para Alteração do Comportamento do Módulo',0,6102);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6102005,'A','                          Prototipação da Gestão de Compras',16,6102);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6103,'S','            GESTÃO DE RECEBIMENTO',0,61);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6103001,'A','                          Cadastro / Revisão de Operações de Recebimento',8,6103);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6103002,'A','                          Sugestão de CST',8,6103);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6103003,'A','                          Sugestão de Operações para Recebimento',8,6103);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6103004,'A','                          Desenvolvimento de Regras Levantadas para Alteração do Comportamento do Módulo',0,6103);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6103005,'A','                          Prototipação da Gestão de Recebimentos',48,6103);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (62,'S','       MERCADO',0,6);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6201,'S','            GESTÃO DE VENDAS',0,62);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6201001,'A','                          Parâmetros por Filiais',8,6201);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6201002,'A','                          Cadastro / Revisão de Operações de Pedido de Venda',8,6201);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6201003,'A','                          Desenvolvimento de Regras Levantadas para Alteração do Comportamento do Módulo',0,6201);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6201004,'A','                          Prototipação da Gestão de Vendas',56,6201);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6201005,'A','                          Geração de Pedidos por EDI',96,6201);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6201006,'A','                          Cálculo da Base de Comissão',40,6201);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6201007,'A','                          Sugestão do Representante por Linha',32,6201);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6202,'S','            GESTÃO DE FATURAMENTO',0,62);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6202001,'A','                          Cadastro / Revisão de Operações de Faturamento',8,6202);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6202002,'A','                          Sugestão de CST',8,6202);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6202003,'A','                          Sugestão de Operações para Faturamento',8,6202);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6202004,'A','                          Sugestão de Mensagens para Faturamento',8,6202);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6202005,'A','                          Desenvolvimento de Regras Levantadas para Alteração do Comportamento do Módulo',0,6202);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6202006,'A','                          Prototipação da Gestão de Faturamento',48,6202);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6203,'S','            GESTÃO DE DISTRIBUIÇÃO',0,62);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6203001,'A','                          Cadastro / Revisão de Parâmetros Formação de Carga',0,6203);
INSERT INTO categoria (id, analiticoSintetico, descricao, quantidadeHoras, categoria_pai) VALUES (6203005,'A','                          Prototipação da Gestão de Distribuição',0,6203);
